USE misa_payroll;

-- Xóa dữ liệu cũ nếu cần chạy lại
-- TRUNCATE TABLE pa_salary_composition;

INSERT INTO pa_salary_composition
(CompositionId, CompositionCode, CompositionName, OrganizationId, ComponentType, Nature, TaxOption, AllowExceedQuota, Quota, ValueType, ValueSource, ValueFormula, Description, ShowOnPayslip, SourceType, SystemId, Status)
VALUES
-- ===== THU NHẬP CỐ ĐỊNH =====
(UUID(),'LUONG_CB','Lương cơ bản','org-001','income','fixed','taxable',0,NULL,'money','manual','5000000','Lương cơ bản theo hợp đồng','yes','system','sys-001','active'),
(UUID(),'LUONG_DONG_BH','Lương đóng bảo hiểm','org-001','income','fixed','taxable',0,NULL,'money','manual','5000000','Lương dùng để tính BHXH/BHYT/BHTN','yes','system','sys-002','active'),
(UUID(),'PC_AN_TRUA','Phụ cấp ăn trưa','org-001','income','fixed','exempt_full',0,'730000','money','manual','730000','Phụ cấp ăn trưa theo tháng','yes','manual',NULL,'active'),
(UUID(),'PC_DI_LAI','Phụ cấp đi lại','org-001','income','fixed','exempt_full',0,'500000','money','manual','500000','Phụ cấp đi lại hàng tháng','yes','manual',NULL,'active'),
(UUID(),'PC_DIEN_THOAI','Phụ cấp điện thoại','org-001','income','fixed','exempt_full',0,'300000','money','manual','300000','Phụ cấp điện thoại','yes','manual',NULL,'active'),
(UUID(),'PC_XANG_XE','Phụ cấp xăng xe','org-001','income','fixed','exempt_full',0,'200000','money','manual','200000','Phụ cấp xăng xe hàng tháng','yes','manual',NULL,'active'),
(UUID(),'PC_NHA_O','Phụ cấp nhà ở','org-001','income','fixed','exempt_full',0,'1000000','money','manual','1000000','Phụ cấp nhà ở hàng tháng','yes','manual',NULL,'active'),
(UUID(),'PC_THAM_NIEN','Phụ cấp thâm niên','org-001','income','fixed','taxable',0,'200000','money','manual','200000','Phụ cấp thâm niên công tác','yes','manual',NULL,'active'),
(UUID(),'PC_TRACH_NHIEM','Phụ cấp trách nhiệm','org-001','income','fixed','taxable',0,'1500000','money','manual','1500000','Phụ cấp chức vụ trách nhiệm','yes','manual',NULL,'active'),
(UUID(),'PC_CHUC_VU','Phụ cấp chức vụ','org-001','income','fixed','taxable',0,'2000000','money','manual','2000000','Phụ cấp theo chức vụ quản lý','yes','manual',NULL,'active'),
(UUID(),'PC_KHU_VUC','Phụ cấp khu vực','org-001','income','fixed','exempt_full',0,'500000','money','manual','500000','Phụ cấp khu vực địa lý','yes','manual',NULL,'active'),
(UUID(),'PC_DOC_HAI','Phụ cấp độc hại','org-001','income','fixed','exempt_full',0,'400000','money','manual','400000','Phụ cấp môi trường độc hại','yes','manual',NULL,'active'),
(UUID(),'PC_NANG_NHOC','Phụ cấp nặng nhọc','org-001','income','fixed','exempt_full',0,'350000','money','manual','350000','Phụ cấp công việc nặng nhọc','yes','manual',NULL,'active'),
(UUID(),'PC_HOT_DONG','Phụ cấp hoạt động','org-001','income','fixed','taxable',0,'300000','money','manual','300000','Phụ cấp hoạt động phí','yes','manual',NULL,'active'),
(UUID(),'PC_CON_NHO','Phụ cấp con nhỏ','org-001','income','fixed','exempt_full',0,'200000','money','manual','200000','Phụ cấp nuôi con nhỏ dưới 6 tuổi','yes','manual',NULL,'active'),
(UUID(),'PC_NGUOI_THAN','Phụ cấp người thân','org-001','income','fixed','exempt_full',0,'300000','money','manual','300000','Phụ cấp người thân phụ thuộc','yes','manual',NULL,'active'),
(UUID(),'PC_CA_DEM','Phụ cấp ca đêm','org-001','income','fixed','exempt_full',0,'150000','money','manual','150000','Phụ cấp làm ca đêm','yes','manual',NULL,'active'),
(UUID(),'PC_CA_3','Phụ cấp ca 3','org-001','income','fixed','exempt_full',0,'180000','money','manual','180000','Phụ cấp ca 3 (22h-6h)','yes','manual',NULL,'active'),
(UUID(),'PC_TIEM_AN','Phụ cấp tiền ăn','org-001','income','fixed','exempt_full',0,'680000','money','manual','680000','Phụ cấp tiền ăn giữa ca','yes','manual',NULL,'active'),
(UUID(),'PC_DONG_PHUC','Phụ cấp đồng phục','org-001','income','fixed','exempt_full',0,'100000','money','manual','100000','Phụ cấp đồng phục hàng tháng','yes','manual',NULL,'active'),

-- ===== THU NHẬP BIẾN ĐỔI =====
(UUID(),'THUONG_HIEU_SUAT','Thưởng hiệu suất','org-001','income','variable','taxable',0,NULL,'money','manual',NULL,'Thưởng theo KPI hiệu suất','yes','manual',NULL,'active'),
(UUID(),'THUONG_DOANH_SO','Thưởng doanh số','org-001','income','variable','taxable',0,NULL,'money','manual',NULL,'Thưởng đạt doanh số tháng','yes','manual',NULL,'active'),
(UUID(),'THUONG_TET','Thưởng lễ tết','org-001','income','variable','taxable',0,NULL,'money','manual',NULL,'Thưởng tết âm lịch và các dịp lễ','yes','manual',NULL,'active'),
(UUID(),'THUONG_DU_AN','Thưởng dự án','org-001','income','variable','taxable',0,NULL,'money','manual',NULL,'Thưởng hoàn thành dự án','yes','manual',NULL,'active'),
(UUID(),'THUONG_SANG_KIEN','Thưởng sáng kiến','org-001','income','variable','taxable',0,NULL,'money','manual',NULL,'Thưởng sáng kiến cải tiến','yes','manual',NULL,'active'),
(UUID(),'THUONG_CUOI_NAM','Thưởng cuối năm','org-001','income','variable','taxable',0,NULL,'money','manual',NULL,'Thưởng tháng lương thứ 13','yes','manual',NULL,'active'),
(UUID(),'THUONG_VƯỢT_KH','Thưởng vượt kế hoạch','org-001','income','variable','taxable',0,NULL,'money','manual',NULL,'Thưởng khi vượt kế hoạch đề ra','yes','manual',NULL,'active'),
(UUID(),'LUONG_TANG_CA','Lương tăng ca','org-001','income','variable','taxable',0,NULL,'money','manual',NULL,'Lương làm thêm giờ ngoài giờ hành chính','yes','manual',NULL,'active'),
(UUID(),'LUONG_NGHI_LE','Lương ngày lễ','org-001','income','variable','taxable',0,NULL,'money','manual',NULL,'Lương làm việc ngày lễ tết','yes','manual',NULL,'active'),
(UUID(),'HOA_HONG_BAN_HANG','Hoa hồng bán hàng','org-001','income','variable','taxable',0,NULL,'money','manual',NULL,'Hoa hồng theo doanh số bán hàng','yes','manual',NULL,'active'),
(UUID(),'HOA_HONG_DOANH_SO','Hoa hồng doanh số','org-001','income','variable','taxable',0,NULL,'money','manual',NULL,'Hoa hồng theo tỷ lệ doanh số đạt được','yes','manual',NULL,'active'),
(UUID(),'HT_DAO_TAO','Hỗ trợ đào tạo','org-001','income','variable','exempt_full',0,NULL,'money','manual',NULL,'Hỗ trợ chi phí đào tạo nâng cao','yes','manual',NULL,'active'),
(UUID(),'HT_HOC_PHI','Hỗ trợ học phí','org-001','income','variable','exempt_full',0,NULL,'money','manual',NULL,'Hỗ trợ học phí cho con em CBNV','no','manual',NULL,'active'),
(UUID(),'TC_SINH_NHAT','Trợ cấp sinh nhật','org-001','income','variable','exempt_full',0,NULL,'money','manual',NULL,'Trợ cấp nhân dịp sinh nhật','yes','manual',NULL,'active'),
(UUID(),'TC_HIEU_HI','Trợ cấp hiếu hỉ','org-001','income','variable','exempt_full',0,NULL,'money','manual',NULL,'Trợ cấp khi hiếu hỉ','yes','manual',NULL,'active'),
(UUID(),'TC_OM_DAU','Trợ cấp ốm đau','org-001','income','variable','exempt_full',0,NULL,'money','manual',NULL,'Trợ cấp khi ốm đau dài ngày','yes','manual',NULL,'active'),
(UUID(),'TC_THAI_SAN','Trợ cấp thai sản','org-001','income','variable','exempt_full',0,NULL,'money','manual',NULL,'Trợ cấp thai sản ngoài BHXH','yes','manual',NULL,'active'),
(UUID(),'PC_CHUYEN_CAN','Phụ cấp chuyên cần','org-001','income','variable','exempt_full',0,NULL,'money','manual',NULL,'Phụ cấp chuyên cần đi làm đầy đủ','yes','manual',NULL,'active'),
(UUID(),'PC_LAM_DEM','Phụ cấp làm đêm','org-001','income','variable','exempt_full',0,NULL,'money','manual',NULL,'Phụ cấp làm việc ban đêm','yes','manual',NULL,'active'),

-- ===== THU NHẬP THEO CÔNG THỨC =====
(UUID(),'LUONG_NGAY','Lương theo ngày','org-001','income','formula','taxable',0,NULL,'money','manual','=LUONG_CB/26','Lương tính theo ngày công','yes','manual',NULL,'active'),
(UUID(),'LUONG_GIO','Lương theo giờ','org-001','income','formula','taxable',0,NULL,'money','manual','=LUONG_NGAY/8','Lương tính theo giờ công','yes','manual',NULL,'active'),
(UUID(),'TONG_THU_NHAP','Tổng thu nhập','org-001','income','formula','taxable',0,NULL,'money','manual','=LUONG_CB+TONG_PHU_CAP+THUONG_HIEU_SUAT','Tổng thu nhập trước khi khấu trừ','yes','manual',NULL,'active'),
(UUID(),'TONG_PHU_CAP','Tổng phụ cấp','org-001','income','formula','exempt_full',0,NULL,'money','manual','=SUM(PC_AN_TRUA,PC_DI_LAI,PC_DIEN_THOAI,PC_XANG_XE)','Tổng các khoản phụ cấp','no','manual',NULL,'active'),
(UUID(),'LUONG_THUC_LANH','Lương thực lãnh','org-001','income','formula','taxable',0,NULL,'money','manual','=TONG_THU_NHAP-TONG_KHAU_TRU','Lương thực tế nhận về','yes','manual',NULL,'active'),
(UUID(),'LUONG_NET','Lương NET','org-001','income','formula','taxable',0,NULL,'money','manual','=LUONG_GROSS-THUE_TNCN-BHXH-BHYT-BHTN','Lương sau khi trừ thuế và bảo hiểm','yes','manual',NULL,'active'),
(UUID(),'LUONG_GROSS','Lương GROSS','org-001','income','formula','taxable',0,NULL,'money','manual','=LUONG_CB+TONG_PHU_CAP','Lương trước khi trừ các khoản','yes','manual',NULL,'active'),
(UUID(),'HH_DOANH_SO_TT','Hoa hồng DS thực tế','org-001','income','formula','taxable',0,NULL,'money','manual','=DOANH_SO_THUC_TE*0.02','Hoa hồng 2% trên doanh số thực tế','yes','manual',NULL,'active'),
(UUID(),'THUONG_VUOT_DS','Thưởng vượt doanh số','org-001','income','formula','taxable',0,NULL,'money','manual','=IF(TY_LE_DS>1,(TY_LE_DS-1)*LUONG_CB*0.5,0)','Thưởng khi vượt 100% doanh số','yes','manual',NULL,'active'),
(UUID(),'PC_THAM_NIEN_TH','Phụ cấp thâm niên (tính)','org-001','income','formula','taxable',0,NULL,'money','manual','=THAM_NIEN_NAM*LUONG_CB*0.01','Phụ cấp thâm niên 1%/năm','yes','manual',NULL,'active'),

-- ===== KHẤU TRỪ =====
(UUID(),'BHXH','Bảo hiểm xã hội','org-001','deduction','formula','taxable',0,'8%','percent','manual','=LUONG_DONG_BH*0.08','BHXH người lao động đóng 8%','yes','system','sys-003','active'),
(UUID(),'BHYT','Bảo hiểm y tế','org-001','deduction','formula','taxable',0,'1.5%','percent','manual','=LUONG_DONG_BH*0.015','BHYT người lao động đóng 1.5%','yes','system','sys-004','active'),
(UUID(),'BHTN','Bảo hiểm thất nghiệp','org-001','deduction','formula','taxable',0,'1%','percent','manual','=LUONG_DONG_BH*0.01','BHTN người lao động đóng 1%','yes','system','sys-005','active'),
(UUID(),'THUE_TNCN','Thuế TNCN','org-001','deduction','formula','taxable',0,NULL,'money','manual',NULL,'Thuế thu nhập cá nhân','yes','system','sys-006','active'),
(UUID(),'CONG_DOAN','Công đoàn','org-001','deduction','formula','taxable',0,'1%','percent','manual','=LUONG_CB*0.01','Đoàn phí công đoàn 1%','yes','system','sys-009','active'),
(UUID(),'KHAU_TRU_DI_MUON','Khấu trừ đi muộn','org-001','deduction','variable','taxable',0,NULL,'money','manual',NULL,'Khấu trừ khi đi làm muộn','yes','manual',NULL,'active'),
(UUID(),'KHAU_TRU_VE_SOM','Khấu trừ về sớm','org-001','deduction','variable','taxable',0,NULL,'money','manual',NULL,'Khấu trừ khi về sớm','yes','manual',NULL,'active'),
(UUID(),'KHAU_TRU_VANG','Khấu trừ vắng mặt','org-001','deduction','variable','taxable',0,NULL,'money','manual',NULL,'Khấu trừ ngày vắng không phép','yes','manual',NULL,'active'),
(UUID(),'PHAT_VI_PHAM','Phạt vi phạm','org-001','deduction','variable','taxable',0,NULL,'money','manual',NULL,'Phạt vi phạm nội quy công ty','yes','manual',NULL,'active'),
(UUID(),'PHAT_MAT_THIET_BI','Phạt mất thiết bị','org-001','deduction','variable','taxable',0,NULL,'money','manual',NULL,'Phạt khi để mất tài sản công ty','yes','manual',NULL,'active'),
(UUID(),'TAM_UNG','Tạm ứng lương','org-001','deduction','variable','taxable',0,NULL,'money','manual',NULL,'Trừ tạm ứng lương đã nhận','yes','manual',NULL,'active'),
(UUID(),'TAM_UNG_CONG_TAC','Tạm ứng công tác phí','org-001','deduction','variable','taxable',0,NULL,'money','manual',NULL,'Trừ tạm ứng công tác phí chưa thanh toán','yes','manual',NULL,'active'),
(UUID(),'TONG_KHAU_TRU','Tổng khấu trừ','org-001','deduction','formula','taxable',0,NULL,'money','manual','=BHXH+BHYT+BHTN+THUE_TNCN+CONG_DOAN','Tổng các khoản khấu trừ bắt buộc','yes','manual',NULL,'active'),
(UUID(),'KHAU_TRU_MUON_TH','Khấu trừ muộn (tính)','org-001','deduction','formula','taxable',0,NULL,'money','manual','=SO_LAN_DI_MUON*50000','Khấu trừ 50k/lần đi muộn','yes','manual',NULL,'active'),

-- ===== CHẤM CÔNG =====
(UUID(),'NGAY_CONG_THUC_TE','Ngày công thực tế','org-001','attendance','variable','taxable',0,NULL,'number','manual',NULL,'Số ngày công thực tế trong tháng','yes','manual',NULL,'active'),
(UUID(),'NGAY_CONG_QUY_DINH','Ngày công quy định','org-001','attendance','fixed','taxable',0,'26','number','manual','26','Số ngày công quy định trong tháng','yes','manual',NULL,'active'),
(UUID(),'SO_GIO_LAM_THEM','Số giờ làm thêm','org-001','attendance','variable','taxable',0,NULL,'number','manual',NULL,'Tổng số giờ làm thêm trong tháng','yes','manual',NULL,'active'),
(UUID(),'SO_NGAY_NGHI_PHEP','Số ngày nghỉ phép','org-001','attendance','variable','taxable',0,NULL,'number','manual',NULL,'Số ngày nghỉ phép có hưởng lương','yes','manual',NULL,'active'),
(UUID(),'SO_NGAY_NGHI_OM','Số ngày nghỉ ốm','org-001','attendance','variable','taxable',0,NULL,'number','manual',NULL,'Số ngày nghỉ ốm trong tháng','yes','manual',NULL,'active'),
(UUID(),'SO_NGAY_NGHI_LE','Số ngày nghỉ lễ','org-001','attendance','variable','taxable',0,NULL,'number','manual',NULL,'Số ngày nghỉ lễ tết theo luật','yes','manual',NULL,'active'),
(UUID(),'SO_LAN_DI_MUON','Số lần đi muộn','org-001','attendance','variable','taxable',0,NULL,'number','manual',NULL,'Số lần đi làm muộn trong tháng','yes','manual',NULL,'active'),
(UUID(),'SO_LAN_VE_SOM','Số lần về sớm','org-001','attendance','variable','taxable',0,NULL,'number','manual',NULL,'Số lần về sớm trong tháng','yes','manual',NULL,'active'),
(UUID(),'SO_NGAY_NGHI_KHONG_PHEP','Ngày nghỉ không phép','org-001','attendance','variable','taxable',0,NULL,'number','manual',NULL,'Số ngày nghỉ không xin phép','yes','manual',NULL,'active'),
(UUID(),'TY_LE_CONG','Tỷ lệ công','org-001','attendance','formula','taxable',0,NULL,'percent','manual','=NGAY_CONG_THUC_TE/NGAY_CONG_QUY_DINH','Tỷ lệ ngày công thực tế/quy định','yes','manual',NULL,'active'),
(UUID(),'SO_NGAY_NGHI_HUONG_LUONG','Ngày nghỉ hưởng lương','org-001','attendance','variable','taxable',0,NULL,'number','manual',NULL,'Số ngày nghỉ vẫn được hưởng lương','yes','manual',NULL,'active'),
(UUID(),'CONG_LAM_THEM_NGAY_LE','Công làm thêm ngày lễ','org-001','attendance','variable','taxable',0,NULL,'number','manual',NULL,'Số ngày làm thêm vào ngày lễ','yes','manual',NULL,'active'),

-- ===== DOANH SỐ =====
(UUID(),'DOANH_SO_THUC_TE','Doanh số thực tế','org-001','sales','variable','taxable',0,NULL,'money','manual',NULL,'Doanh số bán hàng thực tế trong tháng','yes','manual',NULL,'active'),
(UUID(),'DOANH_SO_MUC_TIEU','Doanh số mục tiêu','org-001','sales','fixed','taxable',0,NULL,'money','manual',NULL,'Doanh số mục tiêu được giao tháng','yes','manual',NULL,'active'),
(UUID(),'TY_LE_DS','Tỷ lệ hoàn thành DS','org-001','sales','formula','taxable',0,NULL,'percent','manual','=DOANH_SO_THUC_TE/DOANH_SO_MUC_TIEU','Tỷ lệ % hoàn thành doanh số','yes','system','sys-008','active'),
(UUID(),'SO_DON_HANG','Số đơn hàng','org-001','sales','variable','taxable',0,NULL,'number','manual',NULL,'Tổng số đơn hàng trong tháng','yes','manual',NULL,'active'),
(UUID(),'DOANH_SO_VOT_KH','Doanh số vượt kế hoạch','org-001','sales','formula','taxable',0,NULL,'money','manual','=MAX(DOANH_SO_THUC_TE-DOANH_SO_MUC_TIEU,0)','Phần doanh số vượt mục tiêu','yes','manual',NULL,'active'),
(UUID(),'DOANH_SO_QUY','Doanh số quý','org-001','sales','variable','taxable',0,NULL,'money','manual',NULL,'Tổng doanh số 3 tháng trong quý','yes','manual',NULL,'active'),
(UUID(),'GIA_TRI_HOP_DONG','Giá trị hợp đồng','org-001','sales','variable','taxable',0,NULL,'money','manual',NULL,'Tổng giá trị hợp đồng ký được','yes','manual',NULL,'active'),
(UUID(),'KHACH_HANG_MOI','Số khách hàng mới','org-001','sales','variable','taxable',0,NULL,'number','manual',NULL,'Số khách hàng mới phát triển được','yes','manual',NULL,'active'),
(UUID(),'TY_LE_CHUYEN_DOI','Tỷ lệ chuyển đổi','org-001','sales','formula','taxable',0,NULL,'percent','manual','=SO_DON_HANG/TONG_LEADS','Tỷ lệ chuyển đổi từ leads sang đơn hàng','yes','manual',NULL,'active'),
(UUID(),'DOANH_SO_TRUNG_BINH','DS trung bình/đơn','org-001','sales','formula','taxable',0,NULL,'money','manual','=DOANH_SO_THUC_TE/SO_DON_HANG','Giá trị trung bình mỗi đơn hàng','yes','manual',NULL,'active'),

-- ===== THÔNG TIN NHÂN VIÊN =====
(UUID(),'THAM_NIEN_THANG','Thâm niên (tháng)','org-001','employee_info','variable','taxable',0,NULL,'number','manual',NULL,'Số tháng thâm niên công tác','no','system','sys-007','active'),
(UUID(),'THAM_NIEN_NAM','Thâm niên (năm)','org-001','employee_info','formula','taxable',0,NULL,'number','manual','=THAM_NIEN_THANG/12','Số năm thâm niên công tác','no','manual',NULL,'active'),
(UUID(),'BAC_LUONG','Bậc lương','org-001','employee_info','variable','taxable',0,NULL,'number','manual',NULL,'Bậc lương hiện tại của nhân viên','yes','manual',NULL,'active'),
(UUID(),'HE_SO_LUONG','Hệ số lương','org-001','employee_info','variable','taxable',0,NULL,'number','manual',NULL,'Hệ số lương theo bậc','yes','manual',NULL,'active'),
(UUID(),'LUONG_TOI_THIEU_VUNG','Lương tối thiểu vùng','org-001','employee_info','fixed','taxable',0,'4680000','money','manual','4680000','Lương tối thiểu vùng I năm 2024','yes','manual',NULL,'active'),
(UUID(),'SO_NGUOI_PHU_THUOC','Số người phụ thuộc','org-001','employee_info','variable','taxable',0,NULL,'number','manual',NULL,'Số người phụ thuộc để tính giảm trừ thuế','yes','manual',NULL,'active'),
(UUID(),'GIAM_TRU_GIA_CANH','Giảm trừ gia cảnh','org-001','employee_info','formula','taxable',0,NULL,'money','manual','=11000000+SO_NGUOI_PHU_THUOC*4400000','Giảm trừ gia cảnh bản thân + người phụ thuộc','yes','manual',NULL,'active'),
(UUID(),'THU_NHAP_CHIU_THUE','Thu nhập chịu thuế','org-001','employee_info','formula','taxable',0,NULL,'money','manual','=TONG_THU_NHAP-GIAM_TRU_GIA_CANH-BHXH-BHYT-BHTN','Thu nhập tính thuế TNCN','yes','manual',NULL,'active'),
(UUID(),'MA_SO_THUE','Mã số thuế','org-001','employee_info','variable','taxable',0,NULL,'text','manual',NULL,'Mã số thuế cá nhân của nhân viên','no','manual',NULL,'active'),
(UUID(),'SO_TK_NGAN_HANG','Số tài khoản ngân hàng','org-001','employee_info','variable','taxable',0,NULL,'text','manual',NULL,'Số tài khoản nhận lương','no','manual',NULL,'active'),

-- ===== KHÁC =====
(UUID(),'TIEN_COM_CA','Tiền cơm ca','org-001','other','fixed','exempt_full',0,'25000','money','manual','25000','Tiền cơm mỗi ca làm việc','yes','manual',NULL,'active'),
(UUID(),'TIEN_THUONG_THI_DUA','Tiền thưởng thi đua','org-001','other','variable','exempt_full',0,NULL,'money','manual',NULL,'Tiền thưởng từ quỹ thi đua khen thưởng','yes','manual',NULL,'active'),
(UUID(),'QUY_CONG_DOAN_CTY','Quỹ công đoàn công ty','org-001','other','formula','taxable',0,'2%','percent','manual','=TONG_QUY_LUONG*0.02','Trích quỹ công đoàn 2% từ tổng quỹ lương','no','manual',NULL,'active'),
(UUID(),'BHXH_CTY','BHXH công ty đóng','org-001','other','formula','taxable',0,'17%','percent','manual','=LUONG_DONG_BH*0.17','BHXH phần công ty đóng 17%','no','manual',NULL,'active'),
(UUID(),'BHYT_CTY','BHYT công ty đóng','org-001','other','formula','taxable',0,'3%','percent','manual','=LUONG_DONG_BH*0.03','BHYT phần công ty đóng 3%','no','manual',NULL,'active'),
(UUID(),'BHTN_CTY','BHTN công ty đóng','org-001','other','formula','taxable',0,'1%','percent','manual','=LUONG_DONG_BH*0.01','BHTN phần công ty đóng 1%','no','manual',NULL,'active'),
(UUID(),'TONG_CHI_PHI_CTY','Tổng chi phí công ty','org-001','other','formula','taxable',0,NULL,'money','manual','=TONG_THU_NHAP+BHXH_CTY+BHYT_CTY+BHTN_CTY','Tổng chi phí công ty chi cho 1 nhân viên','no','manual',NULL,'active'),
(UUID(),'TIEN_PHONG_LAM_VIEC','Tiền phòng làm việc','org-001','other','fixed','taxable',0,NULL,'money','manual',NULL,'Chi phí phòng làm việc phân bổ','no','manual',NULL,'active'),
(UUID(),'KINH_PHI_CONG_DOAN','Kinh phí công đoàn NLĐ','org-001','other','formula','taxable',0,'1%','percent','manual','=LUONG_CB*0.01','Kinh phí công đoàn người lao động đóng','yes','manual',NULL,'active'),
(UUID(),'PHU_CAP_DIEU_CHINH','Phụ cấp điều chỉnh','org-001','other','variable','taxable',0,NULL,'money','manual',NULL,'Phụ cấp điều chỉnh đặc thù','yes','manual',NULL,'active'),

-- ===== NGỪNG SỬ DỤNG (inactive) =====
(UUID(),'PC_MAY_TINH_CU','Phụ cấp máy tính (cũ)','org-001','income','fixed','exempt_full',0,'200000','money','manual','200000','Phụ cấp máy tính (đã thay bằng PC_DIEN_THOAI)','yes','manual',NULL,'inactive'),
(UUID(),'LUONG_KHOAN','Lương khoán (cũ)','org-001','income','variable','taxable',0,NULL,'money','manual',NULL,'Lương khoán theo sản phẩm (đã ngừng)','yes','manual',NULL,'inactive'),
(UUID(),'THUONG_QUY','Thưởng quý (cũ)','org-001','income','variable','taxable',0,NULL,'money','manual',NULL,'Thưởng theo quý (đã gộp vào thưởng năm)','yes','manual',NULL,'inactive'),
(UUID(),'BHXH_TU_NGUYEN','BHXH tự nguyện (cũ)','org-001','deduction','formula','taxable',0,NULL,'percent','manual',NULL,'BHXH tự nguyện (đã ngừng chính sách)','yes','manual',NULL,'inactive'),
(UUID(),'PC_XE_BUS','Phụ cấp xe bus (cũ)','org-001','income','fixed','exempt_full',0,'100000','money','manual','100000','Phụ cấp xe bus (đã gộp vào PC_DI_LAI)','yes','manual',NULL,'inactive'),
(UUID(),'TC_KHO_KHAN','Trợ cấp khó khăn (cũ)','org-001','income','variable','exempt_full',0,NULL,'money','manual',NULL,'Trợ cấp khó khăn đột xuất (đã ngừng)','yes','manual',NULL,'inactive'),
(UUID(),'PHAT_TRE_HAN','Phạt trễ hạn (cũ)','org-001','deduction','variable','taxable',0,NULL,'money','manual',NULL,'Phạt trễ hạn nộp báo cáo (đã ngừng áp dụng)','yes','manual',NULL,'inactive'),
(UUID(),'PC_SACH_BONG','Phụ cấp sách vở (cũ)','org-002','income','fixed','exempt_full',0,'50000','money','manual','50000','Phụ cấp sách vở văn phòng phẩm (đã ngừng)','yes','manual',NULL,'inactive'),
(UUID(),'LUONG_HIEU_SUAT_CU','Lương hiệu suất (cũ)','org-002','income','formula','taxable',0,NULL,'money','manual','=LUONG_CB*TY_LE_HS','Lương tính theo hiệu suất (thay bằng THUONG_HIEU_SUAT)','yes','manual',NULL,'inactive'),
(UUID(),'KHAU_TRU_BONG_DA','Khấu trừ bóng đá (cũ)','org-001','deduction','variable','taxable',0,NULL,'money','manual',NULL,'Khấu trừ tham gia giải bóng đá (đã ngừng)','yes','manual',NULL,'inactive'),

-- ===== ĐƠN VỊ KHÁC =====
(UUID(),'LUONG_CB_IT','Lương cơ bản IT','org-002','income','fixed','taxable',0,NULL,'money','manual','8000000','Lương cơ bản phòng IT','yes','manual',NULL,'active'),
(UUID(),'PC_KIEM_NGHIEM','Phụ cấp kiêm nghiệm','org-002','income','fixed','taxable',0,'500000','money','manual','500000','Phụ cấp kiêm nhiệm nhiều vị trí','yes','manual',NULL,'active'),
(UUID(),'THUONG_CODE_DEP','Thưởng code đẹp','org-002','income','variable','taxable',0,NULL,'money','manual',NULL,'Thưởng review code chất lượng cao','yes','manual',NULL,'active'),
(UUID(),'LUONG_CB_HR','Lương cơ bản HR','org-003','income','fixed','taxable',0,NULL,'money','manual','6000000','Lương cơ bản phòng Nhân sự','yes','manual',NULL,'active'),
(UUID(),'PC_TUYEN_DUNG','Phụ cấp tuyển dụng','org-003','income','variable','taxable',0,NULL,'money','manual',NULL,'Phụ cấp khi tuyển dụng thành công','yes','manual',NULL,'active'),
(UUID(),'THUONG_GIU_CHAN','Thưởng giữ chân NV','org-003','income','variable','exempt_full',0,NULL,'money','manual',NULL,'Thưởng retention nhân viên','yes','manual',NULL,'active'),
(UUID(),'LUONG_CB_ACC','Lương cơ bản kế toán','org-004','income','fixed','taxable',0,NULL,'money','manual','7000000','Lương cơ bản phòng Kế toán','yes','manual',NULL,'active'),
(UUID(),'PC_KIEM_TOAN','Phụ cấp kiểm toán','org-004','income','fixed','taxable',0,'1000000','money','manual','1000000','Phụ cấp mùa kiểm toán','yes','manual',NULL,'active'),
(UUID(),'THUONG_QUYET_TOAN','Thưởng quyết toán thuế','org-004','income','variable','taxable',0,NULL,'money','manual',NULL,'Thưởng hoàn thành quyết toán thuế đúng hạn','yes','manual',NULL,'active'),
(UUID(),'TIEN_CONG_TAC_PHI','Tiền công tác phí','org-001','other','variable','exempt_full',0,NULL,'money','manual',NULL,'Chi phí đi công tác được thanh toán','yes','manual',NULL,'active'),
(UUID(),'TIEN_PHEP_NAM','Tiền phép năm còn lại','org-001','income','formula','taxable',0,NULL,'money','manual','=SO_NGAY_PHEP_CON*LUONG_NGAY','Tiền thanh toán phép năm chưa nghỉ','yes','manual',NULL,'active'),
(UUID(),'LUONG_THOI_VIEC','Lương thôi việc','org-001','other','variable','exempt_full',0,NULL,'money','manual',NULL,'Trợ cấp thôi việc theo luật','yes','manual',NULL,'active'),
(UUID(),'TIEN_THUE_NHA','Tiền thuê nhà','org-001','income','fixed','taxable',0,NULL,'money','manual',NULL,'Hỗ trợ tiền thuê nhà cho CBNV ngoại tỉnh','yes','manual',NULL,'active'),
(UUID(),'PC_BIEN_GIOI','Phụ cấp biên giới','org-001','income','fixed','exempt_full',0,'700000','money','manual','700000','Phụ cấp công tác vùng biên giới','yes','manual',NULL,'active'),
(UUID(),'PC_HAI_DAO','Phụ cấp hải đảo','org-001','income','fixed','exempt_full',0,'1000000','money','manual','1000000','Phụ cấp công tác hải đảo','yes','manual',NULL,'active'),
(UUID(),'TIEN_TAU_XE','Tiền tàu xe','org-001','other','variable','exempt_full',0,NULL,'money','manual',NULL,'Chi phí tàu xe đi công tác','yes','manual',NULL,'active'),
(UUID(),'PHU_CAP_TIENG_ANH','Phụ cấp tiếng Anh','org-001','income','fixed','taxable',0,'500000','money','manual','500000','Phụ cấp thông thạo tiếng Anh','yes','manual',NULL,'active'),
(UUID(),'PHU_CAP_NGOAI_NGU','Phụ cấp ngoại ngữ','org-001','income','fixed','taxable',0,'300000','money','manual','300000','Phụ cấp thành thạo ngoại ngữ khác','yes','manual',NULL,'active'),
(UUID(),'TIEN_PHONG_KS','Tiền phòng khách sạn','org-001','other','variable','exempt_full',0,NULL,'money','manual',NULL,'Chi phí phòng khách sạn khi công tác','yes','manual',NULL,'active'),
(UUID(),'TIEN_AN_CONG_TAC','Tiền ăn công tác','org-001','other','variable','exempt_full',0,NULL,'money','manual',NULL,'Chi phí ăn uống khi đi công tác','yes','manual',NULL,'active'),
(UUID(),'PHU_CAP_SINH_HOAT','Phụ cấp sinh hoạt','org-001','income','fixed','exempt_full',0,'200000','money','manual','200000','Phụ cấp sinh hoạt phí','yes','manual',NULL,'active'),
(UUID(),'TONG_LUONG_QUY','Tổng lương quý','org-001','income','formula','taxable',0,NULL,'money','manual','=LUONG_THANG_1+LUONG_THANG_2+LUONG_THANG_3','Tổng lương 3 tháng trong quý','no','manual',NULL,'active'),
(UUID(),'LUONG_BINH_QUAN','Lương bình quân','org-001','income','formula','taxable',0,NULL,'money','manual','=TONG_LUONG_QUY/3','Lương bình quân 3 tháng để tính BHXH','yes','manual',NULL,'active'),
(UUID(),'SO_NGAY_PHEP_CON','Số ngày phép còn','org-001','employee_info','formula','taxable',0,NULL,'number','manual','=NGAY_PHEP_NAM-SO_NGAY_NGHI_PHEP','Số ngày phép năm chưa sử dụng','yes','manual',NULL,'active'),
(UUID(),'TONG_LEADS','Tổng số leads','org-001','sales','variable','taxable',0,NULL,'number','manual',NULL,'Tổng số leads tiếp cận trong tháng','yes','manual',NULL,'active'),
(UUID(),'DOANH_SO_TRUNG_BINH_THANG','DS trung bình tháng','org-001','sales','formula','taxable',0,NULL,'money','manual','=DOANH_SO_QUY/3','Doanh số trung bình mỗi tháng trong quý','yes','manual',NULL,'active');
